# -- TRABAJO PRACTICO INTEGRADOR - PROGRAMACION II -- #

CREATE DATABASE foodstore;
USE foodstore;

# --- TABLA CATEGORIA ---
CREATE TABLE categoria (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
descripcion VARCHAR(100) NOT NULL,

eliminado BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

# --- TABLA PRODUCTO ---
CREATE TABLE producto (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
precio DECIMAL(10,2) NOT NULL CHECK (precio >= 0),
descripcion VARCHAR(100) NOT NULL,
stock INTEGER NOT NULL CHECK (stock >= 0),
imagen VARCHAR(150) NOT NULL,
disponible BOOLEAN NOT NULL DEFAULT FALSE,

eliminado BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

id_categoria INTEGER NOT NULL,
FOREIGN KEY(id_categoria) REFERENCES categoria(id)
);

# --- TABLA USUARIO ---
CREATE TABLE usuario (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL,
apellido VARCHAR(30) NOT NULL,
mail VARCHAR(50) NOT NULL UNIQUE,
celular VARCHAR(20) NOT NULL UNIQUE,
contrasena VARCHAR(20) NOT NULL,
rol VARCHAR(20) NOT NULL,

eliminado BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

# --- TABLA PEDIDO ---
CREATE TABLE pedido (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
estado VARCHAR(20) NOT NULL,
total DECIMAL(10,2) NOT NULL CHECK (total >= 0),
forma_pago VARCHAR(20) NOT NULL,

eliminado BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

id_usuario INTEGER NOT NULL,
FOREIGN KEY(id_usuario) REFERENCES usuario(id)
);

# --- TABLA DETALLE PEDIDO ---
CREATE TABLE detalle_pedido (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
cantidad INTEGER NOT NULL CHECK (cantidad > 0),
subtotal DECIMAL(10,2) NOT NULL CHECK (subtotal >= 0),

eliminado BOOLEAN NOT NULL DEFAULT FALSE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

id_producto INTEGER NOT NULL,
FOREIGN KEY(id_producto) REFERENCES producto(id),

id_pedido INTEGER NOT NULL,
FOREIGN KEY(id_pedido) REFERENCES pedido(id)
);

# -- CREAR UN USUARIO -- (para la conexion)
CREATE USER 'foodstore_user'@'localhost' IDENTIFIED BY 'user_password';
GRANT SELECT, INSERT, UPDATE, DELETE ON foodstore.* TO 'foodstore_user'@'localhost';
FLUSH PRIVILEGES;
